optimizer:
  name: "adamw"
  lr: !!float 1e-3
  weight_decay: !!float 1e-6

lr_scheduler:
  name: "multi_step"
  milestones: [200, 1600]
  gamma: 0.1
  # name: 'identity'

  # name: "plateau"
  # mode: "min"
  # threshold: !!float 5e-6 # l1
  # min_lr: !!float 1e-6
  # patience: 30
  # factor: !!float 0.2
  # cooldown: 10

max_norm: 0.03
ema_decay: 0.999

path:
  wv3_train_path: "/volsparse1/dataset/PanCollection/training_data/train_wv3_9714.h5"
  wv3_val_path: "/volsparse1/dataset/PanCollection/test_data/test_wv3_multiExm1.h5"

  gf2_train_path: "/volsparse1/dataset/PanCollection/training_data/train_gf2_19809.h5"
  gf2_val_path: "/volsparse1/dataset/PanCollection/test_data/test_gf2_multiExm1.h5"

  cave_x4_train_path: "/volsparse1/dataset/HISR/cave_x4/train_cave(with_up)x4.h5"
  cave_x4_val_path: "/volsparse1/dataset/HISR/cave_x4/test_cave(with_up)x4.h5"

  cave_x8_train_path: "/volsparse1/dataset/HISR/cave_x8/train_cave(with_up)x8_rgb_16.h5"
  cave_x8_val_path: "/volsparse1/dataset/HISR/cave_x8/test_cave(with_up)x8_rgb.h5"

  harvard_x4_train_path: "/Data2/ZiHanCao/datasets/HISI/new_harvard/train_harvard(with_up)x4_rgb.h5"
  harvard_x4_val_path: "/Data2/ZiHanCao/datasets/HISI/new_harvard/test_harvard(with_up)x4_rgb.h5"

  harvard_x8_train_path: "/volsparse1/dataset/HISR/harvard_x8/train_harvard(with_up)x8_rgb.h5"
  harvard_x8_val_path: "/volsparse1/dataset/HISR/harvard_x8/test_harvard(with_up)x8_rgb.h5"

network_configs:
  n_colors: 31
  upscale_factor: 8

logger_config:
  base_path: ./log_file/
  name: reciprocal_transformer
  file_mode: w
