optimizer:
  name: 'adam'
  lr: !!float 1e-4
  weight_decay: !!float 1e-4

max_norm: 0.003

lr_scheduler:
  name: 'identity'

path:
  train_path: '/home/ZiHanCao/datasets/HISI/new_cave/train_cave(with_up)x4.h5'
  val_path: '/home/ZiHanCao/datasets/HISI/new_cave/validation_cave(with_up)x4.h5'

network_configs:
  in_c: 31
  out_c: 31
  rgb_c: 3
  factor: 4
  is_dhp_ms: no
  lr_size: 16
  feature_sum: no