optimizer:
  name: "adamw"
  lr: !!float 1e-3
  weight_decay: !!float 1e-6

lr_scheduler:
  #  name: 'cos_anneal'
  #  name: 'cos_anneal_restart'
  #  T_0: 50
  #  T_mult: 2
  #  eta_min: !!float 1e-9
  #  T_max: 2000
  #  eta_min: !!float 1e-8

  name: "plateau"
  mode: "min"
  threshold: !!float 1e-5 # l1
  min_lr: !!float 1e-6
  patience: 10
  factor: !!float 0.1
  cooldown: 5
  threshold_mode: "rel"

  # name: "multi_step"
  # milestones: [800] #[100, 800]
  # gamma: 0.2

max_norm: 0.03
ema_decay: 0.999

path:
  wv3_train_path: "/volsparse1/dataset/PanCollection/training_data/train_wv3_9714.h5"
  wv3_val_path: "/volsparse1/dataset/PanCollection/test_data/test_wv3_multiExm1.h5"

  gf2_train_path: "/volsparse1/dataset/PanCollection/training_data/train_gf2_19809.h5"
  gf2_val_path: "/Data2/ZiHanCao/datasets/pansharpening/gf/reduced_examples/test_gf2_multiExm1.h5"
  #  val_path: '/home/ZiHanCao/datasets/pansharpening/gf/training_gf2/valid_gf2.h5'

  qb_train_path: "/Data2/ZiHanCao/datasets/pansharpening/qb/training_qb/train_qb.h5"
  qb_val_path: "/Data2/ZiHanCao/datasets/pansharpening/qb/reduced_examples/test_qb_multiExm1.h5"

  cave_x4_train_path: "/Data2/ZiHanCao/datasets/HISI/new_cave/train_cave(with_up)x4.h5"
  #   val_path: "/home/ShangqiDeng/data/HSI/cave_x4/test_cavepatches64-2.h5"
  cave_x4_val_path: "/Data2/ZiHanCao/datasets/HISI/new_cave/test_cave(with_up)x4.h5"

  cave_x8_train_path: "/volsparse1/dataset/HISR/cave_x8/train_cave(with_up)x8_rgb_16.h5"
  #  val_path: "/home/ZiHanCao/datasets/HISI/new_cave/x8/validation_cave(with_up)x8_rgb.h5"
  cave_x8_val_path: "/volsparse1/dataset/HISR/cave_x8/test_cave(with_up)x8_rgb.h5"

  harvard_x4_train_path: "/Data2/ZiHanCao/datasets/HISI/new_harvard/train_harvard(with_up)x4_rgb.h5"
  harvard_x4_val_path: "/Data2/ZiHanCao/datasets/HISI/new_harvard/test_harvard(with_up)x4_rgb.h5"

  harvard_x8_train_path: "/volsparse1/dataset/HISR/harvard_x8/train_harvard(with_up)x8_rgb.h5"
  harvard_x8_val_path: "/volsparse1/dataset/HISR/harvard_x8/test_harvard(with_up)x8_rgb.h5"

network_configs:
  img_channel: 8
  condition_channel: 1
  out_channel: 8
  # nano config
  # width: 8
  # middle_blk_num: 1
  # enc_blk_nums: [1, 1, 1]
  # dec_blk_nums: [1, 1, 1]
  # ssm_convs: [11, 9, 7]
  # drop_path_rate: 0.0

  ## small config
  # width: 16
  # middle_blk_num: 2
  # enc_blk_nums: [2,2,2]
  # dec_blk_nums: [2,2,2]
  # ssm_convs: [11, 9, 7]
  # drop_path_rate: 0.1

  ## base config
  width: 32
  naf_enc_blk_nums: []
  naf_dec_blk_nums: []
  naf_chan_upscale: []

  middle_blk_nums: 2

  ssm_enc_blk_nums: [2, 2, 2]
  ssm_dec_blk_nums: [2, 2, 2]
  ssm_chan_upscale: [2, 2, 2]
  window_sizes: [8,8,8]
  ssm_convs: [[3,11], [3,11], [3,11]]
  ssm_d_states: [32, 32, 32]
  drop_path_rate: 0.1

  if_abs_pos: no # buggy: convergence is slow
  if_rope: no
  use_prev_ssm_state: yes
  patch_merge: yes
  upscale: 4

logger_config:
  base_path: ./log_file/
  name: panMamba
  file_mode: w
