optimizer:
  name: "adamw"
  lr: !!float 1e-3
  weight_decay: !!float 1e-6

lr_scheduler:
  #  name: 'cos_anneal'
  #  name: 'cos_anneal_restart'
  #  T_0: 50
  #  T_mult: 2
  #  eta_min: !!float 1e-9
  #  T_max: 2000
  #  eta_min: !!float 1e-8
  # name: "plateau"
  # mode: "min"
  # threshold: !!float 1e-6 # l1
  # min_lr: !!float 1e-8
  # patience: 50
  # factor: !!float 0.2
  # cooldown: 50
  name: "multi_step"
  milestones: [100, 1000] #[100, 800]
  gamma: 0.1

max_norm: 0.3

path:
  train_path: "/Data2/ZiHanCao/datasets/pansharpening/wv3/training_wv3/train_wv3.h5"
  val_path: "/Data2/ZiHanCao/datasets/pansharpening/wv3/reduced_examples/test_wv3_multiExm1.h5"

  #  train_path: '/Data2/ZiHanCao/datasets/pansharpening/gf/training_gf2/train_gf2.h5'
  #  val_path: "/Data2/ZiHanCao/datasets/pansharpening/gf/reduced_examples/test_gf2_multiExm1.h5"
  #  val_path: '/home/ZiHanCao/datasets/pansharpening/gf/training_gf2/valid_gf2.h5'

  # train_path: '/Data2/ZiHanCao/datasets/pansharpening/qb/training_qb/train_qb.h5'
  # val_path: '/Data2/ZiHanCao/datasets/pansharpening/qb/reduced_examples/test_qb_multiExm1.h5'

  #  train_path: "/Data2/ZiHanCao/datasets/HISI/new_cave/train_cave(with_up)x4.h5"
  #   val_path: "/home/ShangqiDeng/data/HSI/cave_x4/test_cavepatches64-2.h5"
  #  val_path: "/Data2/ZiHanCao/datasets/HISI/new_cave/test_cave(with_up)x4.h5"

  #  train_path: "/home/ShangqiDeng/data/HSI/cave_x8/train_cave(with_up)x8_rgb.h5"
  #  val_path: "/home/ZiHanCao/datasets/HISI/new_cave/x8/validation_cave(with_up)x8_rgb.h5"

  # train_path: "/Data2/ShangqiDeng/data/HSI/cave_x8/train_cave(with_up)x8_rgb_16.h5"
  # val_path: "/Data2/ShangqiDeng/data/HSI/cave_x8/test_cavepatches128-2.h5"
  # val_path: "/Data2/ZiHanCao/datasets/HISI/new_cave/x8/test_cave(with_up)x8_rgb.h5"

  # train_path: "/Data2/ZiHanCao/datasets/HISI/new_harvard/x8/train_harvard(with_up)x8_rgb.h5"
  # val_path: "/Data2/ZiHanCao/datasets/HISI/new_harvard/x8/test_clip_128.h5"
  # val_path: "/Data2/ZiHanCao/datasets/HISI/new_harvard/x8/test_harvard(with_up)x8_rgb.h5"

  # train_path: "/Data2/ShangqiDeng/data/HSI/harvard_x8/train_harvard(with_up)x8_rgb.h5"
  # val_path: "/Data2/ShangqiDeng/data/HSI/harvard_x8/test_harvard(with_up)x8_rgb.h5"

  # train_path: '/Data2/ZiHanCao/datasets/HISI/new_harvard/train_harvard(with_up)x4_rgb.h5'
  # val_path: '/Data2/ZiHanCao/datasets/HISI/new_harvard/validation_harvard(with_up)x4_rgb.h5'

  # train_path: '/home/ZiHanCao/datasets/FLIR/train_vis_ir.h5'
  # val_path: '/home/ZiHanCao/datasets/FLIR/val_vis_ir.h5'

  # base_dir: '/Data2/ZiHanCao/datasets/RoadSceneFusion_1'
#  base_dir: "/Data2/ZiHanCao/datasets/RoadScene_and_TNO/"

network_configs:
  img_channel: 8
  condition_channel: 1
  out_channel: 8
  width: 32
  middle_blk_num: 3
  enc_blk_nums: [3,3,3]
  dec_blk_nums: [3,3,3]
  drop_path_rate: 0.2
  stack: no
  patch_merge: yes
  
logger_config:
  base_path: ./log_file/
  name: panRWKV
  file_mode: w
