optimizer:
  name: "adamw"
  lr: !!float 1e-4
  weight_decay: !!float 1e-6

lr_scheduler:
  #  name: 'cos_anneal'
  #  name: 'cos_anneal_restart'
  #  T_0: 50
  #  T_mult: 2
  #  eta_min: !!float 1e-9
  #  T_max: 2000
  #  eta_min: !!float 1e-8
  # name: "plateau"
  # mode: "min"
  # threshold: !!float 1e-6 # l1
  # min_lr: !!float 1e-8
  # patience: 50
  # factor: !!float 0.2
  # cooldown: 50
  name: "multi_step"
  milestones: [1500] #[100, 800]
  gamma: 0.1

max_norm: 0.03
ema_decay: 0.999

path:
  wv3_train_path: "/home/czh/dataset/wv3/train_wv3.h5"
  wv3_val_path: "/home/czh/dataset/wv3/test_wv3_multiExm1.h5"

  gf2_train_path: "/home/czh/dataset/gf2/train_gf2.h5"
  gf2_val_path: "/home/czh/dataset/gf2/test_gf2_multiExm1.h5"

  qb_train_path: '/home/czh/dataset/qb/train_qb.h5'
  qb_val_path: '/home/czh/dataset/qb/test_qb_multiExm1.h5'

  cave_x4_train_path: "/home/czh/dataset/cave/x4/train_cave(with_up)x4.h5"
  cave_x4_val_path: "/home/czh/dataset/cave/x4/test_cave(with_up)x4.h5"

  cave_x8_train_path: "/home/czh/dataset/cave/x8/train_cave(with_up)x8_rgb.h5"
  cave_x8_val_path: "/home/czh/dataset/cave/x8/test_cave(with_up)x8_rgb.h5"

  harvard_x4_train_path: "/home/czh/dataset/harvard/x4/train_harvard(with_up)x4_rgb.h5"
  harvard_x4_val_path: "/home/czh/dataset/harvard/x4/test_harvard(with_up)x4_rgb.h5"

  harvard_x8_train_path: "/home/czh/dataset/harvard/x8/train_harvard(with_up)x8_rgb.h5"
  harvard_x8_val_path: "/home/czh/dataset/harvard/x8/test_harvard(with_up)x8_rgb.h5"

network_configs:
  img_channel: 31
  condition_channel: 3
  out_channel: 31
  width: 32
  middle_blk_num: 2
  enc_blk_nums: [2,2,2]
  dec_blk_nums: [2,2,2]
  ssm_convs: [11,11,11] #[11,11,11]
  drop_path_rate: 0.1
  if_abs_pos: no  # buggy: convergence is slow
  if_rope: no
  scale: 8
  stack: no
  patch_merge: yes
  
logger_config:
  base_path: ./log_file/
  name: panRWKV
  file_mode: w
